Django_Clase/hola/Alarmas/urls.py
from django.urls import  path
from . import views

app_name="Alarmas"
urlpatterns = [
    path("", views.index, name="index"),
    path("v2", views.v2, name="v2"),
]

Django_Clase/hola/hola/urls.py
from django.contrib import admin
from django.urls import  path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('principal/', include('principal.urls')),
    path('Alarmas/', include('Alarmas.urls')),
]

Django_Clase/hola/principal/urls.py
from django.urls import path
from . import views

app_name='principal'
urlpatterns=[
    path("", views.holaDjango, name="holaDjango"),
    path('pepe', views.pepe, name="holapepe"),
    path('indice', views.indice, name='indice'),
    path('indice/<str:name>', views.indiceParam, name='indiceParam'),
    path('<str:name>', views.holaTu, name='holaTu'),
    
]

Django_Clase/hola/Alarmas/models.py
from django.db import models

# Create your models here.

Django_Clase/hola/Alarmas/views.py
from django.shortcuts import render


Alarmas= ['5:30', '5:35', '5:40', '5:50']
# Create your views here.
def index(request):
    return render(request, 'Alarmas/index.html', {'Alarmas':Alarmas})

def v2(request):
    return render(request, 'Alarmas/v2.html')

Django_Clase/hola/principal/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def holaDjango(request):
    return HttpResponse("<h1>Hola Django!</h1>")

def pepe(request):
    return HttpResponse("<h1>Hola Pepe!</h1>")

def holaTu(request,name):
    return HttpResponse(f" Hola, {name.capitalize()}!😎")

def indice(request):
    return render(request, "principal/index.html")

def indiceParam(request, name):
    return render(request, "principal/saludo.html", {"name":name.capitalize() #aqui podriamos pasar mas parametros
    })

Django_Clase/hola/Alarmas/templates/Alarmas/index.html
{% extends "Alarmas/layout.html" %}
{% block body %}
    <h1>Alarmas del sistema</h1>
    <ul>
        {% for alarma in Alarmas %}
        <li>{{alarma}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'Alarmas:v2'%}">Agregar nueva alarma</a>
{% endblock %}

Django_Clase/hola/Alarmas/templates/Alarmas/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    
    <title>Alarmas</title>
    
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

Django_Clase/hola/Alarmas/templates/Alarmas/v2.html
{% extends "Alarmas/layout.html" %}
{% block body %}
    <h1>Nueva Alarma</h1>
    <form action="{% url 'Alarmas:index' %}" method="post"> {% csrf_token %}
        <input type="text" name="Alarma">
        <input type="submit" name="Alarma">
    </form>
    <a href="{% url 'Alarmas:index'%}">Ver alarmas</a>
{% endblock %}

Django_Clase/hola/principal/templates/principal/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Plan de turismo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <h1>Puntos interesantes en la visita a Queretaro:</h1>
    <ul>
        <li>Punto 1</li>
        <li>Punto 2</li>
        <li>Punto 3</li>
        <li>Punto 4</li>
    </ul>
</body>
</html>

Django_Clase/hola/principal/templates/principal/saludo.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Hoolaaa!</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    Hola {{name}}! Cómo estas!
</body>
</html>